-- V10__question_status.sql
-- Questions are never hard-deleted. quiz_attempt_items keep the prompt via question_id.

CREATE TABLE question_statuses (
    question_status_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code          varchar(50) NOT NULL UNIQUE
);
INSERT INTO question_statuses (question_status_id, status_code) VALUES
    (1, 'active'),
    (2, 'deactivated');
ALTER TABLE question_statuses ALTER COLUMN question_status_id RESTART WITH 3;

ALTER TABLE questions
    ADD COLUMN question_status_id smallint NOT NULL DEFAULT 1
        REFERENCES question_statuses (question_status_id);
CREATE INDEX idx_questions_question_status_id ON questions (question_status_id);
