-- V14__course_section_content.sql
-- Ordered content blocks (text / code) under course_sections for learning content authoring.

CREATE TABLE content_types (
    content_type_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type_code varchar(50) NOT NULL UNIQUE
);
INSERT INTO content_types (content_type_id, content_type_code) VALUES
    (1, 'text'),
    (2, 'code');
ALTER TABLE content_types ALTER COLUMN content_type_id RESTART WITH 3;

CREATE TABLE course_section_content (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_section_id   uuid NOT NULL REFERENCES course_sections(id) ON DELETE CASCADE,
    body_text           text NOT NULL,
    content_type_id     smallint NOT NULL REFERENCES content_types(content_type_id),
    position            int NOT NULL
);
CREATE INDEX idx_course_section_content_section_position
    ON course_section_content (course_section_id, position);
