-- V22__student_recommendations.sql
-- Persisted student-facing recommendation flags evaluated on each quiz submission.
-- The dashboard does a plain read of active rows; evaluation runs in the post-quiz worker step.
-- target_ref holds the course_section_id for topic-level flags (null for course-level flags).
--
-- recommendation_statuses follows the lookup-table convention from V1: smallint identity PK,
-- status_code varchar, explicit seed IDs so application code can rely on constants.

CREATE TABLE recommendation_statuses (
  recommendation_status_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_code                varchar(50) NOT NULL UNIQUE
);
INSERT INTO recommendation_statuses (recommendation_status_id, status_code) VALUES
  (1, 'active'),
  (2, 'resolved');

CREATE TABLE student_recommendations (
  id                          uuid      PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id                  uuid      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  course_id                   uuid      NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  flag_type                   varchar(64)  NOT NULL,
  target_ref                  uuid,
  recommendation_status_id    smallint  NOT NULL DEFAULT 1
                              REFERENCES recommendation_statuses(recommendation_status_id),
  evidence                    jsonb     NOT NULL DEFAULT '{}',
  triggered_at                timestamptz  NOT NULL DEFAULT now(),
  last_evaluated_at           timestamptz  NOT NULL DEFAULT now(),
  resolved_at                 timestamptz
);

-- Two partial unique indexes handle the nullable target_ref without sentinel values.
CREATE UNIQUE INDEX uq_student_rec_key
  ON student_recommendations (student_id, course_id, flag_type, target_ref)
  WHERE target_ref IS NOT NULL;

CREATE UNIQUE INDEX uq_student_rec_key_null
  ON student_recommendations (student_id, course_id, flag_type)
  WHERE target_ref IS NULL;

-- Dashboard read: filter to active rows for one student+course.
CREATE INDEX idx_student_rec_active
  ON student_recommendations (student_id, course_id)
  WHERE recommendation_status_id = 1;
