-- V2__identity_and_access.sql
-- organizations/users stay uuid (unpredictable growth, generated by the app, not hand-
-- curated); roles/permissions were created in V1 alongside the other lookup tables.
--
-- RBAC: 5 roles · 44 permissions · additive model.
-- Effective access = union of all assigned roles, narrowed by scope in application policy.
-- NestJS checks permission codes, not role names.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name       varchar(255) NOT NULL,
    slug       varchar(255) NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id   uuid NOT NULL REFERENCES organizations(id),
    email             varchar(320) NOT NULL UNIQUE,
    oauth_provider_id smallint NOT NULL REFERENCES oauth_providers(oauth_provider_id),
    oauth_id          varchar(255) NOT NULL,
    full_name         varchar(255),
    created_at        timestamptz NOT NULL DEFAULT now(),
    UNIQUE (oauth_provider_id, oauth_id)
);
CREATE INDEX idx_users_organization_id ON users(organization_id);

CREATE TABLE user_roles (
    user_id    uuid NOT NULL REFERENCES users(id),
    role_id    smallint NOT NULL REFERENCES roles(role_id),
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

CREATE TABLE role_permissions (
    role_id       smallint NOT NULL REFERENCES roles(role_id),
    permission_id smallint NOT NULL REFERENCES permissions(permission_id),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_role_permissions_permission_id ON role_permissions(permission_id);

-- ── Roles ─────────────────────────────────────────────────────────────────────

INSERT INTO roles (role_id, role_name, role_description) VALUES
    (1, 'platform_admin',         'Create and suspend companies; manage global roles and permissions.'),
    (2, 'platform_catalog_admin', 'Curate the community catalogue. Only role that can delete community courses.'),
    (3, 'org_admin',              'Invite users, assign/remove roles, manage private courses, enrol people, org settings.'),
    (4, 'educator',               'Author content, publish community courses, view org learning insights.'),
    (5, 'learner',                'Base role for everyone: take community courses, take assigned private courses, own progress.');

ALTER TABLE roles ALTER COLUMN role_id RESTART WITH 6;

-- ── Permissions ───────────────────────────────────────────────────────────────

INSERT INTO permissions (permission_id, permission_code, permission_description) VALUES
    -- User (self)
    (1,  'user.create.self',          'Register or create own account'),
    (2,  'user.read.self',            'Read own user profile'),
    (3,  'user.update.self',          'Update own user profile'),
    -- User (org / platform)
    (4,  'user.invite',               'Invite a user into the organisation'),
    (5,  'user.read.org',             'Read user profiles within own organisation'),
    (6,  'user.update.org',           'Update user profiles within own organisation'),
    (7,  'user.deactivate',           'Deactivate a user within own organisation'),
    (8,  'user.read.all',             'Read all users across all organisations'),
    -- Roles
    (9,  'role.read',                 'View roles and their assignments'),
    (10, 'role.assign',               'Assign a role to a user'),
    (11, 'role.remove',               'Remove a role from a user'),
    (12, 'role.catalogue.write',      'Create, update or delete roles in the platform catalogue'),
    -- Organisation
    (13, 'org.create',                'Create a new organisation'),
    (14, 'org.read.all',              'Read all organisations'),
    (15, 'org.suspend',               'Suspend an organisation'),
    (16, 'org.read.self',             'Read own organisation profile'),
    (17, 'org.update.self',           'Update own organisation settings'),
    -- Community courses
    (18, 'course.community.read',     'View community courses'),
    (19, 'course.community.create',   'Create a community course'),
    (20, 'course.community.update',   'Update a community course'),
    (21, 'course.community.publish',  'Publish a community course'),
    (22, 'course.community.delete',   'Delete a community course (catalog admin only)'),
    -- Private courses
    (23, 'course.private.create',     'Create a private course'),
    (24, 'course.private.read',       'View private courses within own organisation'),
    (25, 'course.private.update',     'Update a private course'),
    (26, 'course.private.delete',     'Delete a private course'),
    (27, 'course.section.write',      'Create or update course sections'),
    (28, 'course.lesson.write',       'Create or update course lessons'),
    -- Enrollment
    (29, 'enrollment.assign',         'Enrol users onto private courses'),
    (30, 'enrollment.read.self',      'View own enrollments'),
    (31, 'enrollment.withdraw.self',  'Withdraw from own enrollment'),
    -- Questions and quizzes
    (32, 'question.create',           'Create a question'),
    (33, 'question.update',           'Update a question'),
    (34, 'question.delete',           'Delete a question'),
    (35, 'question.metadata.tag',     'Tag questions with bloom level, difficulty or topic'),
    (36, 'quiz.attempt',              'Take a quiz'),
    (37, 'quiz.read.self',            'View own quiz attempts and results'),
    (38, 'quiz.read.org',             'View quiz attempts across own organisation'),
    -- Analytics and interventions
    (39, 'analytics.read.self',       'View own learning analytics'),
    (40, 'analytics.read.org',        'View organisation-level analytics'),
    (41, 'analytics.read.attempts',   'View quiz attempt analytics'),
    (42, 'analytics.read.mastery',    'View mastery level analytics'),
    (43, 'intervention.flag.read',    'View intervention flags'),
    (44, 'intervention.flag.resolve', 'Acknowledge or resolve intervention flags');

ALTER TABLE permissions ALTER COLUMN permission_id RESTART WITH 45;

-- ── Role → Permission mappings ────────────────────────────────────────────────
-- SELECT-based inserts keep this readable and free of hardcoded numeric ids.

-- platform_admin
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM roles r, permissions p
WHERE r.role_name = 'platform_admin' AND p.permission_code IN (
    'user.create.self', 'user.read.self', 'user.update.self',
    'user.read.org', 'user.read.all',
    'role.read', 'role.assign', 'role.remove', 'role.catalogue.write',
    'org.create', 'org.read.all', 'org.suspend', 'org.read.self',
    'course.community.read'
);

-- platform_catalog_admin
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM roles r, permissions p
WHERE r.role_name = 'platform_catalog_admin' AND p.permission_code IN (
    'user.create.self', 'user.read.self', 'user.update.self',
    'course.community.read', 'course.community.create', 'course.community.update',
    'course.community.publish', 'course.community.delete',
    'course.section.write', 'course.lesson.write',
    'question.create', 'question.update', 'question.delete', 'question.metadata.tag'
);

-- org_admin
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM roles r, permissions p
WHERE r.role_name = 'org_admin' AND p.permission_code IN (
    'user.create.self', 'user.read.self', 'user.update.self',
    'user.invite', 'user.read.org', 'user.update.org', 'user.deactivate',
    'role.read', 'role.assign', 'role.remove',
    'org.read.self', 'org.update.self',
    'course.community.read', 'course.community.create',
    'course.community.update', 'course.community.publish',
    'course.private.create', 'course.private.read',
    'course.private.update', 'course.private.delete',
    'course.section.write', 'course.lesson.write',
    'enrollment.assign',
    'question.create', 'question.update', 'question.delete', 'question.metadata.tag',
    'quiz.read.org',
    'analytics.read.self', 'analytics.read.org',
    'analytics.read.attempts', 'analytics.read.mastery',
    'intervention.flag.read', 'intervention.flag.resolve'
);

-- educator
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM roles r, permissions p
WHERE r.role_name = 'educator' AND p.permission_code IN (
    'user.create.self', 'user.read.self', 'user.update.self',
    'user.read.org',
    'org.read.self',
    'course.community.read', 'course.community.create',
    'course.community.update', 'course.community.publish',
    'course.private.create', 'course.private.read',
    'course.private.update', 'course.private.delete',
    'course.section.write', 'course.lesson.write',
    'enrollment.read.self',
    'question.create', 'question.update', 'question.delete', 'question.metadata.tag',
    'quiz.attempt', 'quiz.read.self', 'quiz.read.org',
    'analytics.read.self', 'analytics.read.org',
    'analytics.read.attempts', 'analytics.read.mastery',
    'intervention.flag.read'
);

-- learner
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM roles r, permissions p
WHERE r.role_name = 'learner' AND p.permission_code IN (
    'user.create.self', 'user.read.self', 'user.update.self',
    'org.read.self',
    'course.community.read',
    'enrollment.read.self', 'enrollment.withdraw.self',
    'quiz.attempt', 'quiz.read.self',
    'analytics.read.self'
);
