-- V8__user_status_and_role_scope.sql
-- Users are never hard-deleted. Status is a lookup, like the V1 tables.
-- Rename platform_catalog_admin → community_admin.
-- Drop user.invite (no invite API).

CREATE TABLE user_statuses (
    user_status_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code      varchar(50) NOT NULL UNIQUE
);
INSERT INTO user_statuses (user_status_id, status_code) VALUES
    (1, 'active'),
    (2, 'deactivated');
ALTER TABLE user_statuses ALTER COLUMN user_status_id RESTART WITH 3;

ALTER TABLE users
    ADD COLUMN user_status_id smallint NOT NULL DEFAULT 1
        REFERENCES user_statuses (user_status_id);
CREATE INDEX idx_users_user_status_id ON users (user_status_id);

UPDATE roles
SET role_name = 'community_admin',
    role_description = 'Curate the community catalogue. Only role that can delete community courses.'
WHERE role_name = 'platform_catalog_admin';

UPDATE roles
SET role_description = 'Assign/remove roles, manage private courses, enrol people, org settings.'
WHERE role_name = 'org_admin';

DELETE FROM role_permissions
WHERE permission_id IN (
    SELECT permission_id FROM permissions WHERE permission_code = 'user.invite'
);
DELETE FROM permissions WHERE permission_code = 'user.invite';
