-- V9__org_and_course_status.sql
-- Organisations and courses are never hard-deleted. Status is a lookup, like user_statuses.

CREATE TABLE organization_statuses (
    organization_status_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code              varchar(50) NOT NULL UNIQUE
);
INSERT INTO organization_statuses (organization_status_id, status_code) VALUES
    (1, 'active'),
    (2, 'suspended');
ALTER TABLE organization_statuses ALTER COLUMN organization_status_id RESTART WITH 3;

ALTER TABLE organizations
    ADD COLUMN organization_status_id smallint NOT NULL DEFAULT 1
        REFERENCES organization_statuses (organization_status_id);
CREATE INDEX idx_organizations_organization_status_id ON organizations (organization_status_id);

CREATE TABLE course_statuses (
    course_status_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_code        varchar(50) NOT NULL UNIQUE
);
INSERT INTO course_statuses (course_status_id, status_code) VALUES
    (1, 'active'),
    (2, 'deactivated');
ALTER TABLE course_statuses ALTER COLUMN course_status_id RESTART WITH 3;

ALTER TABLE courses
    ADD COLUMN course_status_id smallint NOT NULL DEFAULT 1
        REFERENCES course_statuses (course_status_id);
CREATE INDEX idx_courses_course_status_id ON courses (course_status_id);
